CarDealershipWeekFive_UnitTests/CarDealership/Models/Car.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CarDealership.Models
{
    public class Car
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Make required")]
        public string Make { get; set; }

        [Required(ErrorMessage = "Model required")]
        public string Model { get; set; }

        [Required(ErrorMessage = "Year required")]
        [RegularExpression(@"^\d{4}$", ErrorMessage = "Invalid year format")]
        public string Year { get; set; }

        public string ImageUrl { get; set; }

        [Required(ErrorMessage = "Title required")]
        public string Title { get; set; }

        public string Description { get; set; }

        [Required(ErrorMessage = "Price Required")]
        [Range(0.00, 1000000.00, ErrorMessage = "Price cannot be negative or larger than $1,000,000")]
        public decimal? Price { get; set; }

        public static implicit operator Car(EntityCar v)
        {
            return new Car
            {
                Id = v.Id,
                Make = v.Make,
                Model = v.Model,
                Year = v.Year,
                ImageUrl = v.ImageUrl,
                Title = v.Title,
                Description = v.Description,
                Price = v.Price
            };
        }
    }
}

CarDealershipWeekFive_UnitTests/CarDealership/Models/ContactForm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CarDealership.Models
{
    public class ContactForm// : IValidatableObject
    {
        // Your task is to:
        //
        // Make all fields required
        // Ensure the Email field contains an '@' symbol
        // Ensure PhoneNumber is in the format: 1-XXX-XXX-XXXX
        // If the Income is less than 10000 and the PurchaseTimeFrameInMonts is greater than 12,
        // generate a model level area that says 'We don't want your business!'

        [Required(ErrorMessage = "Name required")]
        public string Name { get; set; }

        public int PurchaseTimeFrameInMonths { get; set; }

        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Not a valid Phone number")]
        public string PhoneNumber { get; set; }

        [Required(ErrorMessage = "E-mail address required")]
        [RegularExpression(@"^(([^<>()[\]\\.,;:\s@\""]+(\.[^<>()[\]\\.,;:\s@\""]+)*)|(\"".+\""))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$", ErrorMessage = "Invalid e-mail format")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Income required")]
        [RegularExpression(@"^\$?([0-9]{1,3},([0-9]{3},)*[0-9]{3}|[0-9]+)(.[0-9][0-9])?$", ErrorMessage = "Invalid currency format")]
        [Range(20000.00, double.MaxValue, ErrorMessage = "Income must be greater than $20,000.00")]
        public decimal? Income { get; set; }

        //public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        //{
        //    List<ValidationResult> errors = new List<ValidationResult>();



        //    if (Income == null)
        //    {
        //        errors.Add(new ValidationResult("Income must not be null", new string[] { "Income" }));
        //    }

        //    return errors;
        //}
    }
}

CarDealershipWeekFive_UnitTests/CarDealership/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CarDealership.Models
{
    public class User
    {
        public int UserId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string UserMessage { get; set; }
    }
}

CarDealershipWeekFive_UnitTests/CarDealership/Controllers/CarController.cs
using CarDealership.Models;
using CarDealership.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CarDealership.Controllers
{
    public class CarController : Controller
    {
        ICarRepository _repo = new EntityFrameworkCarRepository();

        // GET: Car
        public ActionResult Index()
        {
            var cars = _repo.GetAllCars();
            return View(cars);
        }

        public ActionResult Details(int id)
        {
            var car = _repo.GetCarById(id);
            return View(car);
        }

        public ActionResult CarDetails(string year, string make, string model)
        {
            var cars = _repo.GetAllCars();
            Car car = _repo.GetCarByYearMakeModel(year, make, model);
            if (car == null)
            {
                return View("Index", cars);
            }
            else
            {
                return View("Details", car);
            }
        }

        public ActionResult Add()
        {
            return View(new Car());
        }

        [HttpPost]
        public ActionResult Add(Car newCar)
        {
            if (ModelState.IsValid)
            {
                _repo.AddCar(newCar);
                return RedirectToAction("Index");
            }
            else
            {
                return View("Add");
            }
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            _repo.DeleteCar(id);
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var car = _repo.GetCarById(id);
            return View(car);
        }

        [HttpPost]
        public ActionResult Edit(Car editCar)
        {
            if (ModelState.IsValid)
            {
                _repo.EditCar(editCar);
                return RedirectToAction("Details", editCar);
            }
            else
            {
                return View();
            }
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult LoginUser(string username, string password)
        {
            var user = _repo.LoginUser(username, password);
            ViewBag.User = user;
            if (user == null)
            {
                return View("Login");
            }
            else { 
                var cars = _repo.GetAllCars();
                return View("Index", cars);
            }
        }
    }
}

CarDealershipWeekFive_UnitTests/CarDealership/Controllers/HomeController.cs
using CarDealership.Models;
using CarDealership.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CarDealership.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Contact us using the form below!";

            return View();
        }

        [HttpPost]
        //[RequireHttps]
        public ActionResult Contact(ContactForm contactForm)
        {
            //ViewBag.Message = "Contact us using the form below!";

            if (ModelState.IsValid)
            {
                // yay, send a sales guy an email
                return RedirectToAction("Thanks");
            }
            else
            {
                return View("Contact");
            }
        }

        public ActionResult Thanks()
        {
            return View();
        }
    }
}

CarDealershipWeekFive_UnitTests/CarDealership/Views/Car/Add.cshtml
@model CarDealership.Models.Car

@{
    ViewBag.Title = "Add";
}

@*<script>
    $(function () {
        $('#datething').datepicker();
        $('#accord').accordion();
    });
</script>*@

<div class="page-title">
    Add Car
</div>

@using (Html.BeginForm("Add", "Car", FormMethod.Post, new { @class="form-horizontal" }))
{
    <div>
        @Html.ValidationSummary(true)
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="Make">Make:</label>
        <div class="col-sm-10">
            @Html.TextBoxFor(x => x.Make, new { @class="form-control" })
            @Html.ValidationMessageFor(m => m.Make)
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="Model">Model:</label>
        <div class="col-sm-10">
            @Html.TextBoxFor(x => x.Model, new { @class="form-control" })
            @Html.ValidationMessageFor(m => m.Model)
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="Year">Year:</label>
        <div class="col-sm-10">
            @Html.TextBoxFor(x => x.Year, new { @class="form-control" })
            @Html.ValidationMessageFor(m => m.Year)
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="ImageUrl">Image URL:</label>
        <div class="col-sm-10">
            @Html.TextBoxFor(x => x.ImageUrl, new { @class="form-control" })
            @Html.ValidationMessageFor(m => m.ImageUrl)
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="Title">Title:</label>
        <div class="col-sm-10">
            @Html.TextBoxFor(x => x.Title, new { @class="form-control" })
            @Html.ValidationMessageFor(m => m.Title)
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="Description">Description:</label>
        <div class="col-sm-10">
            @Html.TextBoxFor(x => x.Description, new { @class="form-control" })
            @Html.ValidationMessageFor(m => m.Description)
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="Price">Price:</label>
        <div class="col-sm-10">
            @Html.TextBoxFor(x => x.Price, new { @class="form-control", placeholder="USD" })
            @Html.ValidationMessageFor(m => m.Price)
        </div>
    </div>
    <div class="col-sm-offset-2">
            <button class="btn btn-primary">Submit</button>
    </div>
}

CarDealershipWeekFive_UnitTests/CarDealership/Views/Car/Details.cshtml
@model CarDealership.Models.Car
@{
    ViewBag.Title = "Details";
}
@* we need more details!!! *@

<h3>@Model.Title</h3>

<div class="row">
    <div class="col-md-3">
        <img class="img-responsive full-width" src="@Model.ImageUrl" />
    </div>
    <div class="col-md-9">
        <div class="row">@Model.Make @Model.Model - @Model.Year</div>
        <div class="row">@string.Format("{0:C}", Model.Price)</div>
        <div class="row">
            <div class="col-md-6 col-sm-12 description-padding">
                @Model.Description
            </div>
        </div>
    </div>
</div>

<input type="button" class="btn btn-primary" value="Edit" onclick="location.href='@Url.Action("Edit", new { id = Model.Id })'" />

<form action="/Car/Delete" onsubmit="return confirm('Do you really want to delete this car?');" method="post">
    @Html.HiddenFor(m => m.Id)
    <button class="btn btn-danger">Delete</button>
</form>

CarDealershipWeekFive_UnitTests/CarDealership/Views/Car/Edit.cshtml
@model CarDealership.Models.Car

@{
    ViewBag.Title = "Edit";
}

<div class="page-title">
    Edit Car
</div>

@using (Html.BeginForm("Edit", "Car", FormMethod.Post, new { @class = "form-horizontal" }))
{
    <div>
        @Html.ValidationSummary(true)
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="Make">Make:</label>
        <div class="col-sm-10">
            @Html.TextBoxFor(x => x.Make, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Make)
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="Model">Model:</label>
        <div class="col-sm-10">
            @Html.TextBoxFor(x => x.Model, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Model)
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="Year">Year:</label>
        <div class="col-sm-10">
            @Html.TextBoxFor(x => x.Year, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Year)
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="ImageUrl">Image URL:</label>
        <div class="col-sm-10">
            @Html.TextBoxFor(x => x.ImageUrl, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.ImageUrl)
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="Title">Title:</label>
        <div class="col-sm-10">
            @Html.TextBoxFor(x => x.Title, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Title)
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="Description">Description:</label>
        <div class="col-sm-10">
            @Html.TextBoxFor(x => x.Description, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Description)
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="Price">Price:</label>
        <div class="col-sm-10">
            @Html.TextBoxFor(x => x.Price, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Price)
        </div>
    </div>
    <div class="col-sm-offset-2">
        <button class="btn btn-primary">Submit</button>
    </div>
}

CarDealershipWeekFive_UnitTests/CarDealership/Views/Car/Index.cshtml
@model IEnumerable<CarDealership.Models.Car>

@{
    ViewBag.Title = "Index";
}

<div class="page-title-flat">
    Cars
</div>
@if (ViewBag.User != null)
{
    <h3>@ViewBag.User.UserMessage</h3>
}

<div class="container">

    @for (int i = 0; i < Model.Count(); i = i + 3)
    {
        var ca = Model.ElementAt(i);
        <div class="row">
            <a href="@Url.Action("Details", new { id = ca.Id })">
                <div class="col-sm-4 no-padding car-image-container card" style="background-image: url(@ca.ImageUrl);">
                    <div class="card_content">
                        @ca.Make @ca.Model<br />
                        @ca.Year
                    </div>
                </div>
            </a>
            @if ((i + 1) < Model.Count())
            {
                ca = Model.ElementAt(i + 1);
                <a href="@Url.Action("Details", new { id = ca.Id })">
                    <div class="col-sm-4 no-padding car-image-container card" style="background-image: url(@ca.ImageUrl);">
                        <div class="card_content">
                            @ca.Make @ca.Model<br />
                            @ca.Year
                        </div>
                    </div>
                </a>
            }
            @if ((i + 2) < Model.Count())
            {
                ca = Model.ElementAt(i + 2);
                <a href="@Url.Action("Details", new { id = ca.Id })">
                    <div class="col-sm-4 no-padding car-image-container card" style="background-image: url(@ca.ImageUrl);">
                        <div class="card_content">
                            @ca.Make @ca.Model<br />
                            @ca.Year
                        </div>
                    </div>
                </a>
            }
        </div>
    }

            @*@for (int i = 0; i < Model.Count(); i = i + 3)
            {
                var ca = Model.ElementAt(i);
                <div class="row">
                    <div class="col-md-4">
                        <a href="@Url.Action("Details", new { id = ca.Id })">
                            <img src="@ca.ImageUrl" alt="This is a car for sale" class="car-image" />
                        </a>
                    </div>
                    @if ((i + 1) < Model.Count())
                    {
                        ca = Model.ElementAt(i + 1);
                        <div class="col-md-4">
                            <a href="@Url.Action("Details", new { id = ca.Id })">
                                <img src="@ca.ImageUrl" alt="This is a car for sale" class="car-image" />
                            </a>
                        </div>
                    }
                    @if ((i + 2) < Model.Count())
                    {
                        ca = Model.ElementAt(i + 2);
                        <div class="col-md-4">
                            <a href="@Url.Action("Details", new { id = ca.Id })">
                                <img src="@ca.ImageUrl" alt="This is a car for sale" />
                            </a>
                        </div>
                    }

                </div>
                <div>
                    &nbsp;
                </div>
            }*@
            <div class="text-center top-margin">
                <a href="@Url.Action("Add")" class="btn btn-primary" role="button">
                    Add Car +
                </a>
            </div>
        </div>

<script>
    function CarImageResize() {
        var carImageWidth = $('.car-image-container').width();
        $('.car-image-container').css({
            'height': carImageWidth + 'px'
        });
    }
    
    $(document).ready(CarImageResize());

    (function($) {
        var resizeTimer;
        $(window).resize(function () {
            clearTimeout(resizeTimer);
            resizeTimer = setTimeout(CarImageResize, 50);
        });
    })(jQuery);

    //var cw = $('.car-image-container').width();
    //$('.car-image-container').css({
    //    'height': cw + 'px'
    //});

    //$(window).on('resize', CarImageResize());


    //$(window).on('resize', function() {
    //    var imgWidth = $('.car-image-container').width();
    //    $('.car-image-container').css({
    //        'height': imgWidth + 'px'
    //    });
    //});
</script>

CarDealershipWeekFive_UnitTests/CarDealership/Views/Car/Login.cshtml
@{
    ViewBag.Title = "Login";
}

<script>
    $(function () {
        $('#theForm').submit(function () {
            if ($('#username').val().indexOf("'") > -1) {
                return false;
            }
            return true;
        });
    });
</script>

<h2>Login</h2>

@using (Html.BeginForm("LoginUser", "Car", FormMethod.Post, new { id = "theForm" }))
{
    <div>Username: <input type="text" name="username" id="username" /></div>
    <div>Password: <input type="password" name="password" id="password" /></div>
    <div><input type="submit" value="Login"/></div>
}

CarDealershipWeekFive_UnitTests/CarDealership/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h1 style="font-size:144px;">WE'RE AMAZING</h1>

CarDealershipWeekFive_UnitTests/CarDealership/Views/Home/Contact.cshtml
@model CarDealership.Models.ContactForm

@{
    ViewBag.Title = "Contact";
    var items = new List<SelectListItem>(){
      new SelectListItem() {
          Text = "6 months",
          Value = "6"
      },
            new SelectListItem() {
          Text = "12 months",
          Value = "12"
      },
            new SelectListItem() {
          Text = "24 months",
          Value = "24"
      },
            new SelectListItem() {
          Text = "36 months",
          Value = "36"
      }
    };
}
<div class="page-title">
    Contact
</div>
@*<h3>@ViewBag.Message</h3>*@

@using (Html.BeginForm("Contact", "Home", FormMethod.Post, new { @class = "form-horizontal" }))
{
    <div>
        @Html.ValidationSummary(true)
    </div>
    <div>
        <div class="form-group">
            <label class="control-label col-sm-2" for="Name">Name:</label>
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Name)
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2" for="PhoneNumber">Phone #:</label>
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.PhoneNumber, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.PhoneNumber)
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2" for="Email">E-mail:</label>
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Email)
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2" for="Income">Income:</label>
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.Income, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Income)
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-offset-2 col-sm-10" for="PurchaseTimeFrameInMonths">When are you planning to purchase a car?</label>
            <div class="col-sm-offset-2 col-sm-10">
                @Html.DropDownListFor(x => x.PurchaseTimeFrameInMonths, items, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.PurchaseTimeFrameInMonths)
            </div>
        </div>
        <div class="col-sm-offset-2">
            <button class="btn btn-primary">Submit</button>
        </div>
    </div>
}

CarDealershipWeekFive_UnitTests/CarDealership/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Welcome to the SWCG Car Dealership!</h1>
    <p>Go ahead and look around!</p>
</div>

CarDealershipWeekFive_UnitTests/CarDealership/Views/Home/Thanks.cshtml
@{
    ViewBag.Title = "Thanks";
}

<h2>Thanks!!!!!!!!!!!!!!!!!!!!!!!!!!!!!</h2>